config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: 0..5
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(task_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def task_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>List of all the restaurants</h1>
<ul>
<% @restaurants.each do |r| %>
<li>Restaurant: <%= link_to r.name, restaurant_path(r) %> - address: <%= r.address %> - ph.nr: <%= r.phone_number %> - Type: <%= r.category %></li>
<% end %>
</ul>
<%= link_to 'Add a new Restaurant', '/restaurants/new' %>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %><br>
  <%= t.label :address %>
  <%= t.text_field :address %><br>
  <%= t.label :phone_number %>
  <%= t.text_field :phone_number %><br>
  <%= t.label :category %>
  <%= t.text_field :category %><br>
  <%= t.submit %>
<% end %>
<%= link_to 'Back to list', '/restaurants' %>

app/views/restaurants/show.html.erb
<h1>Restaurant:</h1>

  <tbody>
      <tr>
        <td><%= @restaurant.name %></td><br>
        <td><%= @restaurant.address %></td><br>
        <td><%= @restaurant.phone_number %></td><br>
        <td><%= @restaurant.category %></td><br>
      </tr>

  <%= @reviews %>
  </tbody>
<%= link_to 'Back to list', '/restaurants' %><br>
<%= link_to 'Write a review',  new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h3>Add a new review:</h3>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back to the restaurant', restaurant_path(params[:restaurant_id]) %>

app/views/reviews/show.html.erb
<h3>Reviews:</h3>
<%= @review %>